export interface VocabEntry {
  term: string
  chinese: string
}

export const MATH_VOCABULARY: VocabEntry[] = [
  // --- 基本运算与代数 ---
  { term: 'solve', chinese: '求解' },
  { term: 'evaluate', chinese: '求值' },
  { term: 'simplify', chinese: '化简' },
  { term: 'factorise', chinese: '因式分解' },
  { term: 'expand', chinese: '展开' },
  { term: 'substitute', chinese: '代入' },
  { term: 'expression', chinese: '表达式' },
  { term: 'equation', chinese: '方程' },
  { term: 'inequality', chinese: '不等式' },
  { term: 'identity', chinese: '恒等式' },
  { term: 'variable', chinese: '变量' },
  { term: 'constant', chinese: '常量' },
  { term: 'coefficient', chinese: '系数' },
  { term: 'term', chinese: '项' },
  { term: 'polynomial', chinese: '多项式' },
  { term: 'quadratic', chinese: '二次的' },
  { term: 'cubic', chinese: '三次的' },
  { term: 'linear', chinese: '线性的/一次的' },
  { term: 'simultaneous', chinese: '联立的' },
  { term: 'remainder', chinese: '余数' },
  { term: 'factor', chinese: '因子/因式' },
  { term: 'root', chinese: '根' },
  { term: 'discriminant', chinese: '判别式' },
  { term: 'binomial', chinese: '二项式' },
  { term: 'partial fraction', chinese: '部分分式' },
  { term: 'modulus', chinese: '模/绝对值' },
  { term: 'surd', chinese: '根式(不尽根)' },
  { term: 'rational', chinese: '有理的' },
  { term: 'irrational', chinese: '无理的' },
  { term: 'integer', chinese: '整数' },
  { term: 'reciprocal', chinese: '倒数' },

  // --- 函数与图像 ---
  { term: 'function', chinese: '函数' },
  { term: 'domain', chinese: '定义域' },
  { term: 'range', chinese: '值域' },
  { term: 'inverse', chinese: '反函数/逆' },
  { term: 'composite', chinese: '复合(函数)' },
  { term: 'transformation', chinese: '变换' },
  { term: 'translation', chinese: '平移' },
  { term: 'reflection', chinese: '对称/反射' },
  { term: 'stretch', chinese: '拉伸' },
  { term: 'asymptote', chinese: '渐近线' },
  { term: 'intercept', chinese: '截距' },
  { term: 'sketch', chinese: '画草图' },
  { term: 'turning point', chinese: '极值点/拐点' },
  { term: 'vertex', chinese: '顶点' },
  { term: 'exponential', chinese: '指数的' },
  { term: 'logarithm', chinese: '对数' },
  { term: 'natural logarithm', chinese: '自然对数' },

  // --- 微积分 ---
  { term: 'differentiate', chinese: '求导' },
  { term: 'derivative', chinese: '导数' },
  { term: 'gradient', chinese: '斜率/梯度' },
  { term: 'tangent', chinese: '切线/正切' },
  { term: 'normal', chinese: '法线' },
  { term: 'stationary point', chinese: '驻点' },
  { term: 'maximum', chinese: '最大值' },
  { term: 'minimum', chinese: '最小值' },
  { term: 'inflection', chinese: '拐点' },
  { term: 'monotonic', chinese: '单调的' },
  { term: 'increasing', chinese: '递增的' },
  { term: 'decreasing', chinese: '递减的' },
  { term: 'concave', chinese: '凹的' },
  { term: 'convex', chinese: '凸的' },
  { term: 'integrate', chinese: '积分' },
  { term: 'integration', chinese: '积分' },
  { term: 'definite integral', chinese: '定积分' },
  { term: 'indefinite integral', chinese: '不定积分' },
  { term: 'substitution', chinese: '换元' },
  { term: 'by parts', chinese: '分部积分' },
  { term: 'rate of change', chinese: '变化率' },

  // --- 三角 ---
  { term: 'trigonometric', chinese: '三角函数的' },
  { term: 'radian', chinese: '弧度' },
  { term: 'arc length', chinese: '弧长' },
  { term: 'sector', chinese: '扇形' },
  { term: 'amplitude', chinese: '振幅' },
  { term: 'period', chinese: '周期' },

  // --- 坐标几何 ---
  { term: 'perpendicular', chinese: '垂直的' },
  { term: 'parallel', chinese: '平行的' },
  { term: 'midpoint', chinese: '中点' },
  { term: 'distance', chinese: '距离' },
  { term: 'locus', chinese: '轨迹' },
  { term: 'chord', chinese: '弦' },

  // --- 数列与级数 ---
  { term: 'sequence', chinese: '数列' },
  { term: 'series', chinese: '级数' },
  { term: 'arithmetic', chinese: '等差的' },
  { term: 'geometric', chinese: '等比的' },
  { term: 'common difference', chinese: '公差' },
  { term: 'common ratio', chinese: '公比' },
  { term: 'convergent', chinese: '收敛的' },
  { term: 'divergent', chinese: '发散的' },
  { term: 'sum to infinity', chinese: '无穷级数之和' },
  { term: 'recurrence', chinese: '递推' },

  // --- 统计 ---
  { term: 'probability', chinese: '概率' },
  { term: 'permutation', chinese: '排列' },
  { term: 'combination', chinese: '组合' },
  { term: 'variance', chinese: '方差' },
  { term: 'standard deviation', chinese: '标准差' },
  { term: 'cumulative', chinese: '累积的' },
  { term: 'frequency', chinese: '频率/频数' },
  { term: 'distribution', chinese: '分布' },
  { term: 'hypothesis', chinese: '假设' },
  { term: 'significance', chinese: '显著性' },
  { term: 'correlation', chinese: '相关性' },
  { term: 'regression', chinese: '回归' },
  { term: 'mean', chinese: '均值' },
  { term: 'median', chinese: '中位数' },
  { term: 'quartile', chinese: '四分位数' },
  { term: 'outlier', chinese: '异常值' },
  { term: 'sample', chinese: '样本' },
  { term: 'population', chinese: '总体' },
  { term: 'random variable', chinese: '随机变量' },
  { term: 'binomial distribution', chinese: '二项分布' },
  { term: 'normal distribution', chinese: '正态分布' },
  { term: 'Poisson distribution', chinese: '泊松分布' },
  { term: 'contingency table', chinese: '列联表' },
  { term: 'chi-squared', chinese: '卡方' },
  { term: 'expected frequency', chinese: '期望频数' },

  // --- 向量 ---
  { term: 'vector', chinese: '向量' },
  { term: 'scalar', chinese: '标量' },
  { term: 'magnitude', chinese: '模/大小' },
  { term: 'displacement', chinese: '位移' },
  { term: 'unit vector', chinese: '单位向量' },
  { term: 'position vector', chinese: '位置向量' },
  { term: 'dot product', chinese: '点积' },

  // --- 常见题目指令词 ---
  { term: 'hence', chinese: '由此/因此' },
  { term: 'given that', chinese: '已知' },
  { term: 'show that', chinese: '证明/说明' },
  { term: 'hence or otherwise', chinese: '由此或用其他方法' },
  { term: 'deduce', chinese: '推导' },
  { term: 'determine', chinese: '确定/求出' },
  { term: 'exact value', chinese: '精确值' },
  { term: 'verify', chinese: '验证' },
  { term: 'state', chinese: '写出/陈述' },
  { term: 'prove', chinese: '证明' },
  { term: 'obtain', chinese: '求得' },
  { term: 'express', chinese: '表示为' },
  { term: 'in terms of', chinese: '用…表示' },
  { term: 'respectively', chinese: '分别地' },
  { term: 'denote', chinese: '表示/记为' },
  { term: 'numerator', chinese: '分子' },
  { term: 'denominator', chinese: '分母' },
]
